#!/usr/bin/python3

from sys import argv
from subprocess import call

if len(argv) == 1:
    raise SystemExit

state=0
word=""
write=False
writeln=False
loop=False
loopline=-1
_str=""
cmt=""
vname=""
value=""
quote=""
var={
"cls":"\33c"
}

file=""
fset=False

line=0
col=0

version="2.00"

valid_flags=[
      "-v",
      "-version",
      "-h",
      "-help"
      ]

keyword=[
      "write",
      "writeln",
      "var"
      ]

cur=""

for arg in argv:
   if arg.endswith(".alik"):
      file=arg
      fset=True
   elif arg.startswith("-") and arg in valid_flags:
      if arg == "-v" or arg == "-version":
         print("Current version: {0}".format(version))
         raise SystemExit
      elif arg == "-h" or arg == "-help":
         print(valid_flags)
         raise SystemExit

if fset==False:
    print("USAGE: ./alik [flags] [filename].alik")

with open(file) as rf:
    rf=rf.readlines()
    while True:
        var["cls"]="\33c"
        if line==len(rf):
            break
        cur=rf[line][col]
        if state==0:
            word+=cur
            if word=="write":
                write=True
                word=""
            elif word=="ln":
                if not write:
                    print(f"Error at line {line+1:2}:\
                            'ln' is not a keyword")
                    raise SystemExit
                write=False
                writeln=True
                word=""
            elif word=="loop":
                loop=True
                loopline=line
                word=""
            elif word=="end":
                if loop==True:
                    line=loopline
                    word=""
                else:
                    raise SystemExit
            elif word=="var ":
                state=2
                vset=True
                word=""
            elif cur=="$":
                state=5
                word=""
            elif cur=="\n":
                line+=1
                col=-1
                word=""
            elif cur=="#":
                state=6
                word=""
            elif cur=="{":
                state=7
                word=""
            elif cur in "\"'":
                state=1
                quote=cur
                word=""
        elif state==1:
            if quote==cur:
                if write:
                    print(_str,end="")
                    write=False
                elif writeln:
                    print(_str)
                    writeln=False
                else:
                    print(f"Error at line {line+1:2}:\
                            string not printed")
                    raise SystemExit
                _str=""
                quote=""
                state=0
            else:
                _str+=cur
        elif state==2:
            if cur==" ":
                state=3
            else:
                vname+=cur
        elif state==3:
            if cur==" ":
                pass
            elif cur=="\n":
                if value=="true":
                    var[vname]=True
                elif value=="false":
                    vat[vname]=False
                else:
                    try:
                        var[vname]=int(value)
                    except:
                        var[vname]=float(value)
                line+=1
                col=-1
                vset=False
                vname=""
                value=""
                state=0
            elif cur in "\"'":
                quote=cur
                state=4
            else:
                value+=cur
        elif state==4:
            if cur==quote:
                state=0
                var[vname]=value
                vname=""
                value=""
            else:
                value+=cur
        elif state==5:
            if cur=="\n":
                if write:
                    print(var[vname],end="")
                    write=False
                elif writeln:
                    print(var[vname])
                    writeln=False
                line+=1
                col=-1
                state=0
                vname=""
            else:
                vname+=cur
        elif state==6:
            if cur=="\n":
                state=0
                line+=1
                col=-1
        elif state==7:
            if cur=="\n":
                line+=1
                col=-1
            elif cur=="}":
                state=0
        col+=1
