#!/usr/bin/python3

from sys import argv
from subprocess import call
from string import ascii_letters as alpha

if len(argv) == 1:
   raise SystemExit

file=""
fset=False
run=True

line=0
col=0

state=0
word=""
write=False
writeln=False
_str=""
cmt=""
quote=""

version="1.01"

valid_flags=[
      "-v",
      "-version",
      "-h",
      "-help",
      "-c",
      "-compile"
      ]

keyword=[
      "write",
      "writeln"
      ]

cur=""

for arg in argv:
   if arg.endswith(".alik"):
      file=arg
      fset=True
   elif arg.startswith("-") and arg in valid_flags:
      if arg == "-v" or arg == "-version":
         print("Current version: {0}".format(version))
         raise SystemExit
      elif arg == "-h" or arg == "-help":
         print(valid_flags)
         raise SystemExit
      elif arg == "-c" or arg == "-compile":
         run=True

if fset==False:
   raise SystemExit

with open(file) as rf:
   rf=rf.readlines()
   with open(file[:len(file)-5]+".py","w") as wf:
      while True:
         if line==len(rf):
            break
         cur=rf[line][col]
         if state==0:
            word+=cur
            if word=="write":
               write=True
               wf.write("print(")
               word=""
            elif word=="ln":
               if write:
                  writeln=True
                  write=False
               else:
                  raise SyntaxError("'{0}' is not a keyword".format(word))
               word=""
            elif cur==";":
               if write:
                  wf.write(",end=\"\")")
                  write=False
               elif writeln:
                  wf.write(")")
                  writeln=False
               word=""
            elif cur=="\n":
               wf.write("\n")
               line+=1
               col=-1
               word=""
            elif cur in " \t":
               wf.write(cur)
               word=""
            elif cur in "\"'":
               quote=cur
               state=1
               word=""
            elif cur=="|":
               state=2
               wf.write("#")
               word=""
         elif state==1:
            if cur==quote:
               quote=""
               wf.write("\""+_str+"\"")
               _str=""
               state=0
            else:
               _str+=cur
         elif state==2:
            if cur=="\n":
               wf.write(cmt+"\n")
               cmt=""
               line+=1
               col=-1
               state=0
            else:
               cmt+=cur
         col+=1

if run:
   call(["python3",file[:len(file)-5]+".py"])
   call(["rm",file[:len(file)-5]+".py"])
else:
   pass
